### ISSUE TITLE
Error on closing file dialog

### ISSUE THREAD

**Issue by NJacob** [edggy/pyLemma#16]
Traceback (most recent call last):
  File "main.py", line 80, in <module>
    tstPrf = parsers.defaultProofParser(filename)
  File "/home/jacobn2/Dropbox/PyLemma/PyLemma/pyLemma/parsers.py", line 623, in defaultProofParser
    for n, line in enumerate(string.split('\n')):
AttributeError: 'tuple' object has no attribute 'split'

**Comment by Hubert51** [comment]
I am not very familiar with this part of code. I will try my best to fix it. Do you use python2 to run this code?

**Comment by NJacob** [comment]
Python 2.7, yes.
